import type { Metadata } from "next";
import "@/styles/globals.css";
import { StoreProvider } from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "GitHub Search",
  description: "Generated by Noor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider> {children}</StoreProvider>
      </body>
    </html>
  );
}
